config/routes.rb
Rails.application.routes.draw do
  root 'ideas#index'
  resources :ideas do
    resources :reviews, shallow: true, only: [:create, :edit, :destroy]
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end
 

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    can :manage, Idea do |idea|
        idea.user == user
    end

    can :manage, Review do |review|
        review.user == user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :title, presence: true
  validates :description, presence:true
  belongs_to :user
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :ideas
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def user_signed_in?
    if session[:user_id].present? && current_user.nil?
      session[:user_id] = nil
    end
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def authenticate_user!
    if !user_signed_in?
      redirect_to  new_session_path
    end
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_idea, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, except: [:new, :create, :index, :show]

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new idea_params
    @idea.user = current_user
    if @idea.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @reviews = @idea.reviews.order(created_at: :desc)
    @review = Review.new
  end

  def index
    @ideas = Idea.order(created_at: :desc)
  end

  def destroy
    @idea.destroy
    redirect_to root_path
  end

  def edit
  end

  def update
    @idea.update idea_params
    redirect_to @idea
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description)
  end

  def find_idea
    @idea = Idea.find params[:id]
  end

  def authorize_user!
    # binding.pry
    unless can?(:manage, @post)
      flash[:alert] = "Access Denied!"
      redirect_to root_path
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_review, only: [:destroy]
  before_action :find_idea, only: [:create]
  before_action :authorize_user!, except: [:create]

  def create
    @review = @idea.reviews.build(review_params)
    @review.user = current_user
    @review.save
    redirect_to idea_path(@idea)
  end

  def destroy
    @review.destroy
    redirect_to idea_path(@review.idea_id)
  end

  private
  def review_params
    params.require(:review).permit(:body)
  end

  def find_review
    @review = Review.find(params[:id])
  end

  def find_idea
    @idea = Idea.find(params[:idea_id])
  end

  def authorize_user!
    # binding.pry
    unless can?(:manage, @review)
      redirect_to idea_path(@review.idea_id)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<%= form_for @idea do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control', rows: '5' %>
  </div>

  <div class = 'text-right'>
    <%= f.submit 'Submit', class:"btn btn-outline-primary" %>
  </div>
  
<% end %>

app/views/ideas/edit.html.erb
<div class = "container-fluid mt-3">

  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-3">Edit Idea</h1>
      <%= render 'form' %>
    </div>
  </div>

</div>

app/views/ideas/index.html.erb
<div class = "container-fluid mt-3">

  <div class = "row">
    <% @ideas.each do |idea| %>
      <div class = "col-12">
        <div class="card mt-3">
          <div class="card-body">
            <h4><%= link_to idea.title, idea_path(idea), class: 'card-title' %> </h4>
            <div class='extend-btn'>
              <div class="the-btn hide">
                <%= image_tag 'extend.jpg', style: 'width: 20px; border-radius: 5px;' %>
              </div>
              <div class="the-btn">
                <%= image_tag 'shrink.jpg', style: 'width: 20px; border-radius: 5px;' %>
              </div>
              <div class = 'interior-card'>
                <p class="card-text"><%= idea.description %></p>
                <p class="card-text mt-2"><strong> By: <%= idea.user&.first_name %></strong></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/ideas/new.html.erb
<div class = "container-fluid mt-3">

  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-3">Create New Idea</h1>
      <%= render 'form' %>
    </div>
  </div>

</div>

app/views/ideas/show.html.erb
<div class = "container-fluid mt-3">

  <div class="card">
    <div class="card-body">
      <h4 class="card-title"><%= @idea.title %></h4>

      <p class="card-text mt-2"><%= @idea.description %></p>

      <p class="card-text mt-2"><strong> By: <%= @idea.user&.first_name %></strong></p>

      <% if user_signed_in? && can?(:manage, @idea)%>
        <div class = "text-right">
          <%= link_to 'Edit', edit_idea_path(@idea), class:"btn btn-outline-primary" %>

          <%= link_to(
              'Delete',
              idea_path(@idea),
              data: {confirm: 'Are you sure?'},
              method: :delete,
              class:"btn btn-outline-primary") %>
        </div>
      <% end %>
    </div>
  </div>

  <hr>

  <div class = "container-fluid mt-3">

    <%= form_for [@idea, @review] do |f| %>

      <h4> Leave A Review </h4>
      <div>
        <div class="form-group">
          <%= f.text_area :body, class: 'form-control', rows: '5' %>
        </div>
      </div>
      <div class = 'text-right'>
        <%= f.submit 'Create Review', class:"btn btn-outline-primary" %>
      </div>
    <% end %>

  </div>

  <hr>

  <% @reviews.each do |review| %>
    <div class="card mt-3">
      <div class="card-body">
        <p class="card-text"><%= review.body %> </p>
        <p class="card-text mt-2"><strong> By: <%= review.user&.first_name %></strong></p>
        <% if can?(:manage, review)%>
          <div class = "text-right">
            <%= link_to(
                'Delete',
                review_path(review),
                data: {confirm: 'Are you sure?'},
                method: :delete,
                class:"btn btn-outline-primary") %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaFactory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">

        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Idea Factory', root_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'New Idea', new_idea_path, class: "nav-link" %>
          </li>
        </ul>

        <ul class="navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="nav-item">
              <span class = "nav-link disabled"> Welcome, <%= current_user.first_name %> <%= current_user.last_name %> </span>
            </li>
            <li class="nav-item">
              <%= link_to('Sign Out', session_path, class: 'nav-link', method: :delete) %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_path, class: 'nav-link' %>
            </li>
            <li class="navbar-item">
              <%= link_to 'Login', new_session_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>

    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class = "container-fluid mt-3">

  <div class="jumbotron jumbotron-fluid">
    <div class="container row">
      <div class="col-4">
      </div>
      <div class="col-5">
        <h4>Sign Up</h4>

        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class = 'text-right'>
            <%= f.submit 'Create Account', class:"btn btn-outline-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>